### ISSUE TITLE
Proje hakkında soru

### ISSUE THREAD

**Issue by inoshell** [ibrahimcahit/deneyap_kart_imu_basic_flight_controller#1]
Merhaba,
Projenizi çok beğendim. Ellerinize sağlık.
İleride haberleşme dahil DeneyapKart ile tam takır çalışan bir uçuş kontrolcü kartı yapmayı planlıyor musunuz?

**Comment by ibrahimcahit** [comment]
Merhaba, 

Böyle bir proje en başından beri planımızdaydı ancak kartın geliştirme süreci nedeniyle bir türlü gerçekleşemedi. Teorik olarak Deneyap Kart, üzerindeki sensörü ve Arduino'ya göre güçlü olan işlemcisi sebebiyle, bir quadcopter uçurmaya yetebilir. 

Haberleşme kumanda alıcısı ile yapılacak, çok kompleks bir şey değil, SBUS ya da PPM sinyalini okumak gerekiyor. IMU tarafında da düzgün bir filtreleme gerek.
